sudo: required
services:
  - docker


command: --default-authentication-plugin=mysql_native_password

matrix:
  include:
    - env:
        - DB=mysql:5.5
    - env:
        - DB=mysql:5.6
    - env:
        - DB=mysql:5.7
    - env:
        - DB=mysql:8.0

before_install:
  # bootstrap modules needed to manipulate dist
  - "cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)"
  - "cpanm Module::Build"
  - "cpanm Test::Pod"
  - "cpanm Test::Pod::Coverage"

before_script:
  - bash ./.travis.install-mysql.sh
  - bash ./scripts/semi_install_my_prove.sh

script:
  - bash ./install.sh -h 127.0.0.1 -u mytap -t
  - my_prove -v -u root -h 127.0.0.1 tests/*.my 